2022-04-13 09:47:50,824 (69299/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:47:50,824 (69299/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:47:50,826 (69299/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2022-04-13 09:49:53,252 (69490/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:49:53,252 (69490/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:49:53,261 (69490/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "cemalokten" does not exist\n\n'
2022-04-13 09:50:19,157 (69507/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:50:19,157 (69507/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:50:19,167 (69507/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "cemalokten" does not exist\n\n'
2022-04-13 09:51:50,273 (69673/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:51:50,273 (69673/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:51:50,283 (69673/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "cemalokten" does not exist\n\n'
2022-04-13 09:52:58,390 (69700/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:52:58,391 (69700/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:56:22,282 (69806/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:56:22,283 (69806/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:56:34,939 (69806/MainThread) pgcli.pgexecute ERROR - sql: '/c bug_reporting_dev', error: SyntaxError('syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n')
2022-04-13 09:56:34,940 (69806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n\n'
2022-04-13 10:49:04,960 (69806/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^\n')
2022-04-13 10:49:04,962 (69806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n\n'
2022-04-26 14:30:02,229 (11173/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-26 14:30:02,231 (11173/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-26 14:30:06,364 (11173/MainThread) pgcli.pgexecute ERROR - sql: '/c bug_reporting_dev', error: SyntaxError('syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n')
2022-04-26 14:30:06,365 (11173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n\n'
2022-04-26 14:30:16,669 (11173/MainThread) pgcli.pgexecute ERROR - sql: 'SE', error: SyntaxError('syntax error at or near "SE"\nLINE 1: SE\n        ^\n')
2022-04-26 14:30:16,670 (11173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "SE"\nLINE 1: SE\n        ^\n\n'
2022-04-26 14:31:12,251 (11173/MainThread) pgcli.pgexecute ERROR - sql: 'select id from activities_log WHERE user_name=Israa', error: UndefinedColumn('column "israa" does not exist\nLINE 1: select id from activities_log WHERE user_name=Israa\n                                                      ^\n')
2022-04-26 14:31:12,251 (11173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column "israa" does not exist\nLINE 1: select id from activities_log WHERE user_name=Israa\n                                                      ^\n\n'
2022-04-26 17:25:55,633 (16109/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-26 17:25:55,633 (16109/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-26 17:26:06,357 (16109/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT name FROM projects WHERE name=$1', error: UndefinedParameter('there is no parameter $1\nLINE 1: SELECT name FROM projects WHERE name=$1\n                                             ^\n')
2022-04-26 17:26:06,358 (16109/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedParameter: there is no parameter $1\nLINE 1: SELECT name FROM projects WHERE name=$1\n                                             ^\n\n'
2022-04-26 17:26:11,871 (16109/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT name FROM projects WHERE name=Scouts', error: UndefinedColumn('column "scouts" does not exist\nLINE 1: SELECT name FROM projects WHERE name=Scouts\n                                             ^\n')
2022-04-26 17:26:11,871 (16109/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column "scouts" does not exist\nLINE 1: SELECT name FROM projects WHERE name=Scouts\n                                             ^\n\n'
2022-04-27 08:26:22,813 (1709/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-27 08:26:22,813 (1709/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 08:49:27,249 (30398/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-29 08:49:27,249 (30398/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 08:50:19,708 (30398/MainThread) pgcli.pgexecute ERROR - sql: 'select * from bugs', error: UndefinedTable('relation "bugs" does not exist\nLINE 1: select * from bugs\n                      ^\n')
2022-04-29 08:50:19,709 (30398/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: relation "bugs" does not exist\nLINE 1: select * from bugs\n                      ^\n\n'
2022-04-29 08:52:14,626 (30398/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2022-04-29 08:52:14,627 (30398/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2022-04-29 08:52:30,586 (30447/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-29 08:52:30,586 (30447/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 17:58:19,672 (43388/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-29 17:58:19,673 (43388/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 18:09:24,047 (43388/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT\n      e.*, s.status\n    FROM bugs e\n    JOIN activities_log s ON e.activities_log.bug_id = s.bugs.id WHERE bugs.project_id = 1', error: UndefinedTable('missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON e.activities_log.bug_id = s.bug...\n                                     ^\n')
2022-04-29 18:09:24,050 (43388/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON e.activities_log.bug_id = s.bug...\n                                     ^\n\n'
2022-04-29 18:09:47,179 (43388/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT\n      e.*, s.status\n    FROM bugs e\n    JOIN activities_log s ON s.activities_log.bug_id = e.bugs.id WHERE bugs.project_id = 1', error: UndefinedTable('missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n')
2022-04-29 18:09:47,179 (43388/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n\n'
2022-04-29 18:09:58,762 (43388/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT\n      e.*, s.status\n    FROM bugs e\n    JOIN activities_log s ON s.activities_log.bug_id = e.bugs.id WHERE e.bugs.project_id = 1', error: UndefinedTable('missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n')
2022-04-29 18:09:58,762 (43388/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n\n'
2022-05-11 08:05:45,270 (9644/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 08:05:45,270 (9644/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 08:06:44,331 (9644/MainThread) pgcli.pgexecute ERROR - sql: '\\quit', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\quit\n        ^\n')
2022-05-11 08:06:44,332 (9644/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\quit\n        ^\n\n'
2022-05-11 14:43:15,657 (25729/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:43:15,658 (25729/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:43:16,879 (25729/MainThread) pgcli.pgexecute ERROR - sql: "'", error: SyntaxError('unterminated quoted string at or near "\'"\nLINE 1: \'\n        ^\n')
2022-05-11 14:43:16,880 (25729/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: unterminated quoted string at or near "\'"\nLINE 1: \'\n        ^\n\n'
2022-05-11 14:43:24,821 (25729/MainThread) pgcli.pgexecute ERROR - sql: 'ALTER TABLE bugs\nADD  "github_linksss" VARCHAR,', error: SyntaxError('syntax error at end of input\nLINE 2: ADD  "github_linksss" VARCHAR,\n                                      ^\n')
2022-05-11 14:43:24,822 (25729/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 2: ADD  "github_linksss" VARCHAR,\n                                      ^\n\n'
2022-05-11 14:46:35,453 (25919/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:46:35,453 (25919/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:47:44,871 (25919/MainThread) pgcli.pgexecute ERROR - sql: '\\exit', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n')
2022-05-11 14:47:44,874 (25919/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n\n'
2022-05-11 14:55:03,096 (26928/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:55:03,097 (26928/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:55:12,862 (26928/MainThread) pgcli.main ERROR - sql: '\\c bug_reporting_dev', error: InterfaceError('only protocol 3 supported')
2022-05-11 14:55:12,866 (26928/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-11 14:58:09,728 (27040/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:58:09,729 (27040/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:58:13,257 (27040/MainThread) pgcli.main ERROR - sql: '\\c d4fik3rlo3r184', error: InterfaceError('only protocol 3 supported')
2022-05-11 14:58:13,262 (27040/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-11 15:08:06,480 (27492/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:08:06,481 (27492/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 15:13:29,047 (28134/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:13:29,047 (28134/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 15:13:51,177 (28134/MainThread) pgcli.pgexecute ERROR - sql: 'TRUNCATE TABLE projects', error: FeatureNotSupported('cannot truncate a table referenced in a foreign key constraint\nDETAIL:  Table "bugs" references "projects".\nHINT:  Truncate table "bugs" at the same time, or use TRUNCATE ... CASCADE.\n')
2022-05-11 15:13:51,181 (28134/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.FeatureNotSupported: cannot truncate a table referenced in a foreign key constraint\nDETAIL:  Table "bugs" references "projects".\nHINT:  Truncate table "bugs" at the same time, or use TRUNCATE ... CASCADE.\n\n'
2022-05-11 15:14:58,869 (28134/MainThread) pgcli.pgexecute ERROR - sql: '/q', error: SyntaxError('syntax error at or near "/"\nLINE 1: /q\n        ^\n')
2022-05-11 15:14:58,870 (28134/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /q\n        ^\n\n'
2022-05-11 15:19:04,836 (28296/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:19:04,836 (28296/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 15:20:25,931 (28296/MainThread) pgcli.pgexecute ERROR - sql: '/q', error: SyntaxError('syntax error at or near "/"\nLINE 1: /q\n        ^\n')
2022-05-11 15:20:25,934 (28296/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /q\n        ^\n\n'
2022-05-11 15:29:23,923 (28662/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:29:23,924 (28662/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-16 10:44:24,081 (6427/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-16 10:44:24,081 (6427/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-16 12:11:50,981 (9966/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-16 12:11:50,982 (9966/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-16 12:32:58,614 (9966/MainThread) pgcli.pgexecute ERROR - sql: '\\exit', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n')
2022-05-16 12:32:58,617 (9966/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n\n'
2022-05-18 14:45:23,666 (6021/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 14:45:23,667 (6021/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:37:53,075 (13997/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:37:53,075 (13997/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:40:09,957 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE database shannon-trust', error: SyntaxError('syntax error at or near "-"\nLINE 1: CREATE database shannon-trust\n                               ^\n')
2022-05-18 15:40:09,958 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "-"\nLINE 1: CREATE database shannon-trust\n                               ^\n\n'
2022-05-18 15:40:24,207 (13997/MainThread) pgcli.pgexecute ERROR - sql: "CREATE database 'shannon-trust'", error: SyntaxError('syntax error at or near "\'shannon-trust\'"\nLINE 1: CREATE database \'shannon-trust\'\n                        ^\n')
2022-05-18 15:40:24,207 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\'shannon-trust\'"\nLINE 1: CREATE database \'shannon-trust\'\n                        ^\n\n'
2022-05-18 15:42:01,275 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE database `shannon-trust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE database `shannon-trust`\n                        ^\n')
2022-05-18 15:42:01,276 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE database `shannon-trust`\n                        ^\n\n'
2022-05-18 15:42:15,164 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE `shannon-trust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n')
2022-05-18 15:42:15,164 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n\n'
2022-05-18 15:42:19,266 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE `shannon-trust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n')
2022-05-18 15:42:19,266 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n\n'
2022-05-18 15:42:50,691 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DB `shannon-trust`', error: SyntaxError('syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n')
2022-05-18 15:42:50,692 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n\n'
2022-05-18 15:42:52,378 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DB `shannon-trust`', error: SyntaxError('syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n')
2022-05-18 15:42:52,379 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n\n'
2022-05-18 15:43:19,456 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE [shannon-trust]', error: SyntaxError('syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n')
2022-05-18 15:43:19,456 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n\n'
2022-05-18 15:43:26,044 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE [shannon-trust', error: SyntaxError('syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust\n                        ^\n')
2022-05-18 15:43:26,044 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust\n                        ^\n\n'
2022-05-18 15:43:29,599 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE [shannon-trust]', error: SyntaxError('syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n')
2022-05-18 15:43:29,600 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n\n'
2022-05-18 15:43:39,555 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE `shannontrust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannontrust`\n                        ^\n')
2022-05-18 15:43:39,555 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannontrust`\n                        ^\n\n'
2022-05-18 15:43:51,222 (13997/MainThread) pgcli.pgexecute ERROR - sql: '\\CREATE DATABASE `shannon-trust`', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE `shannon-trust`\n        ^\n')
2022-05-18 15:43:51,223 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE `shannon-trust`\n        ^\n\n'
2022-05-18 15:44:09,297 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^\n')
2022-05-18 15:44:09,298 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n\n'
2022-05-18 15:44:51,648 (14643/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:44:51,649 (14643/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:44:58,104 (14643/MainThread) pgcli.pgexecute ERROR - sql: '\\C shannon-trust', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\C shannon-trust\n        ^\n')
2022-05-18 15:44:58,105 (14643/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\C shannon-trust\n        ^\n\n'
2022-05-18 15:45:09,363 (14652/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:45:09,363 (14652/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:45:16,094 (14652/MainThread) pgcli.main ERROR - sql: '\\connect shannon-trust', error: InterfaceError('only protocol 3 supported')
2022-05-18 15:45:16,095 (14652/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-18 15:45:24,480 (14652/MainThread) pgcli.main ERROR - sql: '\\connect `shannon-trust`', error: InterfaceError('only protocol 3 supported')
2022-05-18 15:45:24,481 (14652/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-18 15:50:32,106 (14733/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:50:32,106 (14733/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:50:41,548 (14733/MainThread) pgcli.pgexecute ERROR - sql: '\\CREATE DATABASE shannon_trust', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE shannon_trust\n        ^\n')
2022-05-18 15:50:41,549 (14733/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE shannon_trust\n        ^\n\n'
2022-05-19 09:18:32,634 (22125/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 09:18:32,635 (22125/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 09:19:38,391 (22125/MainThread) pgcli.pgexecute ERROR - sql: 'quiot', error: SyntaxError('syntax error at or near "quiot"\nLINE 1: quiot\n        ^\n')
2022-05-19 09:19:38,394 (22125/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "quiot"\nLINE 1: quiot\n        ^\n\n'
2022-05-19 14:05:15,356 (32575/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 14:05:15,357 (32575/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 14:12:27,494 (33487/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 14:12:27,495 (33487/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 14:13:52,063 (34045/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 14:13:52,064 (34045/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 14:13:56,688 (34045/MainThread) pgcli.pgexecute ERROR - sql: '1   DROP TYPE IF EXISTS bug_types CASCADE', error: SyntaxError('syntax error at or near "1"\nLINE 1: 1   DROP TYPE IF EXISTS bug_types CASCADE\n        ^\n')
2022-05-19 14:13:56,690 (34045/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "1"\nLINE 1: 1   DROP TYPE IF EXISTS bug_types CASCADE\n        ^\n\n'
2022-05-23 12:25:40,693 (5738/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:25:40,694 (5738/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:25:40,804 (5738/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 12:29:37,386 (6308/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:29:37,387 (6308/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:29:37,438 (6308/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 12:29:44,543 (6319/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:29:44,544 (6319/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:30:13,449 (6319/MainThread) pgcli.pgexecute ERROR - sql: 'drop shannon_trust', error: SyntaxError('syntax error at or near "shannon_trust"\nLINE 1: drop shannon_trust\n             ^\n')
2022-05-23 12:30:13,451 (6319/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "shannon_trust"\nLINE 1: drop shannon_trust\n             ^\n\n'
2022-05-23 12:30:51,918 (6350/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:30:51,918 (6350/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:30:51,973 (6350/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 12:31:14,294 (6758/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:31:14,294 (6758/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:31:25,285 (6758/MainThread) pgcli.pgexecute ERROR - sql: 'select *', error: SyntaxError('SELECT * with no tables specified is not valid\nLINE 1: select *\n               ^\n')
2022-05-23 12:31:25,287 (6758/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: SELECT * with no tables specified is not valid\nLINE 1: select *\n               ^\n\n'
2022-05-23 12:34:14,307 (7248/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:34:14,308 (7248/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:34:14,354 (7248/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 12:34:26,661 (7266/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:34:26,661 (7266/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:34:26,665 (7266/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
2022-05-23 12:34:36,680 (7281/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:34:36,681 (7281/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:34:36,684 (7281/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
2022-05-23 12:34:44,347 (7291/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:34:44,347 (7291/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:34:44,380 (7291/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 12:35:00,363 (7305/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:35:00,363 (7305/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:35:00,403 (7305/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 12:35:03,540 (7319/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 12:35:03,540 (7319/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 12:35:03,559 (7319/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 13:02:48,733 (4578/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:02:48,733 (4578/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:02:48,831 (4578/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5435 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 13:17:42,124 (7158/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:17:42,125 (7158/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:17:42,130 (7158/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5438 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
2022-05-23 13:18:36,455 (7188/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:18:36,457 (7188/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:18:36,532 (7188/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5438 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 13:23:09,183 (8968/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:23:09,183 (8968/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:23:09,217 (8968/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5438 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 13:27:22,545 (10413/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:27:22,546 (10413/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:27:22,606 (10413/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5438 failed: FATAL:  database "shannon_trust" does not exist\n\n'
2022-05-23 13:28:48,911 (10893/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:28:48,911 (10893/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:28:48,916 (10893/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server at "localhost" (::1), port 5438 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at "localhost" (127.0.0.1), port 5438 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n\n'
2022-05-23 13:43:29,883 (4846/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:43:29,884 (4846/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:43:29,910 (4846/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "shannon-trust-db-1" to address: nodename nor servname provided, or not known\n\n'
2022-05-23 13:43:43,378 (4870/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:43:43,378 (4870/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:43:43,382 (4870/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "shannon-trust-db-1" to address: nodename nor servname provided, or not known\n\n'
2022-05-23 13:44:17,206 (4901/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:44:17,206 (4901/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:44:17,209 (4901/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: invalid integer value "12:5432" for connection option "port"\n\n'
2022-05-23 13:45:08,662 (4916/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 13:45:08,662 (4916/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 13:45:08,685 (4916/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "postgres" to address: nodename nor servname provided, or not known\n\n'
2022-05-23 15:47:18,095 (17731/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 15:47:18,096 (17731/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 15:47:18,108 (17731/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "db" to address: nodename nor servname provided, or not known\n\n'
2022-05-23 15:49:31,508 (17801/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 15:49:31,509 (17801/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 15:49:31,529 (17801/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "db" to address: nodename nor servname provided, or not known\n\n'
2022-05-23 15:49:39,165 (17826/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 15:49:39,165 (17826/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 16:37:09,700 (17826/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from users', error: AdminShutdown('terminating connection due to administrator command\n')
2022-05-23 16:37:09,706 (17826/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.AdminShutdown: terminating connection due to administrator command\n\n'
2022-05-23 16:37:09,706 (17826/MainThread) pgcli.main ERROR - sql: 'SELECT * from users', error: AdminShutdown('terminating connection due to administrator command\n')
2022-05-23 16:37:09,707 (17826/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.AdminShutdown: terminating connection due to administrator command\n\n'
2022-05-23 16:37:09,897 (17826/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from users', error: UndefinedTable('relation "users" does not exist\nLINE 1: SELECT * from users\n                      ^\n')
2022-05-23 16:37:09,898 (17826/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.AdminShutdown: terminating connection due to administrator command\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: relation "users" does not exist\nLINE 1: SELECT * from users\n                      ^\n\n'
2022-05-23 16:37:22,936 (18905/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-23 16:37:22,936 (18905/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-23 16:38:15,783 (18905/MainThread) pgcli.pgexecute ERROR - sql: '\\dt', error: AdminShutdown('terminating connection due to administrator command\n')
2022-05-23 16:38:15,786 (18905/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 463, in run\n    response = pgspecial.execute(cur, sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgspecial/main.py", line 117, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgspecial/dbcommands.py", line 468, in list_tables\n    return list_objects(cur, pattern, verbose, ["r", "p", ""])\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgspecial/dbcommands.py", line 459, in list_objects\n    cur.execute(sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.AdminShutdown: terminating connection due to administrator command\n\n'
2022-05-23 16:38:15,786 (18905/MainThread) pgcli.main ERROR - sql: '\\dt', error: AdminShutdown('terminating connection due to administrator command\n')
2022-05-23 16:38:15,787 (18905/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 463, in run\n    response = pgspecial.execute(cur, sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgspecial/main.py", line 117, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgspecial/dbcommands.py", line 468, in list_tables\n    return list_objects(cur, pattern, verbose, ["r", "p", ""])\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgspecial/dbcommands.py", line 459, in list_objects\n    cur.execute(sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.AdminShutdown: terminating connection due to administrator command\n\n'
2022-11-07 17:24:49,157 (21728/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-11-07 17:24:49,158 (21728/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-11-07 17:24:49,160 (21728/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/psycopg/connection.py", line 725, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2022-11-08 09:08:32,132 (1958/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-11-08 09:08:32,132 (1958/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-11-08 09:08:32,136 (1958/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0/libexec/lib/python3.10/site-packages/psycopg/connection.py", line 725, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2023-04-17 12:43:07,818 (68363/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-04-17 12:43:07,818 (68363/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-09 11:57:40,461 (95439/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-06-09 11:57:40,461 (95439/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-09 11:57:46,030 (95439/MainThread) pgcli.pgexecute ERROR - sql: 'connect chiltern', error: SyntaxError('syntax error at or near "connect"\nLINE 1: connect chiltern\n        ^')
2023-06-09 11:57:46,033 (95439/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "connect"\nLINE 1: connect chiltern\n        ^\n'
2023-06-09 11:57:52,894 (95439/MainThread) pgcli.pgexecute ERROR - sql: 'database', error: SyntaxError('syntax error at or near "database"\nLINE 1: database\n        ^')
2023-06-09 11:57:52,894 (95439/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "database"\nLINE 1: database\n        ^\n'
2023-06-09 11:57:55,924 (95439/MainThread) pgcli.pgexecute ERROR - sql: 'database chiltern', error: SyntaxError('syntax error at or near "database"\nLINE 1: database chiltern\n        ^')
2023-06-09 11:57:55,925 (95439/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "database"\nLINE 1: database chiltern\n        ^\n'
2023-06-09 11:58:00,851 (95439/MainThread) pgcli.pgexecute ERROR - sql: 'connect', error: SyntaxError('syntax error at or near "connect"\nLINE 1: connect\n        ^')
2023-06-09 11:58:00,852 (95439/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "connect"\nLINE 1: connect\n        ^\n'
2023-06-09 12:01:17,773 (95439/MainThread) pgcli.pgexecute ERROR - sql: '\\user', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\user\n        ^')
2023-06-09 12:01:17,777 (95439/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\user\n        ^\n'
2023-06-09 12:01:18,933 (95439/MainThread) pgcli.pgexecute ERROR - sql: 'user', error: SyntaxError('syntax error at or near "user"\nLINE 1: user\n        ^')
2023-06-09 12:01:18,933 (95439/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: user\n        ^\n'
2023-06-09 12:04:51,935 (96216/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-06-09 12:04:51,935 (96216/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-09 12:05:09,261 (96216/MainThread) pgcli.pgexecute ERROR - sql: 'select *', error: SyntaxError('SELECT * with no tables specified is not valid\nLINE 1: select *\n               ^')
2023-06-09 12:05:09,264 (96216/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: SELECT * with no tables specified is not valid\nLINE 1: select *\n               ^\n'
2023-06-09 12:05:23,596 (96216/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * FROM projects', error: UndefinedTable('relation "projects" does not exist\nLINE 1: SELECT * FROM projects\n                      ^')
2023-06-09 12:05:23,597 (96216/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "projects" does not exist\nLINE 1: SELECT * FROM projects\n                      ^\n'
2023-06-09 12:06:35,259 (96438/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-06-09 12:06:35,259 (96438/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-09 12:09:11,225 (96438/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^')
2023-06-09 12:09:11,227 (96438/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n'
2023-06-09 12:09:12,004 (96438/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^')
2023-06-09 12:09:12,005 (96438/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n'
2023-06-09 12:09:30,582 (96707/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-06-09 12:09:30,583 (96707/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-06-09 15:16:12,217 (26617/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-06-09 15:16:12,217 (26617/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-31 12:51:31,468 (99164/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-31 12:51:31,469 (99164/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-31 12:51:31,516 (99164/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "cemalokten" does not exist\n'
2023-07-31 12:51:36,701 (99181/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-07-31 12:51:36,701 (99181/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-07-31 12:51:36,706 (99181/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "kb.db" does not exist\n'
2023-08-03 15:27:58,401 (3319/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-08-03 15:27:58,402 (3319/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-08-03 15:27:58,425 (3319/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "cemalokten" does not exist\n'
2023-09-08 21:56:35,051 (70265/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-09-08 21:56:35,051 (70265/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-09-08 21:56:51,684 (70265/MainThread) pgcli.pgexecute ERROR - sql: 'selct * from urls', error: SyntaxError('syntax error at or near "selct"\nLINE 1: selct * from urls\n        ^')
2023-09-08 21:56:51,687 (70265/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "selct"\nLINE 1: selct * from urls\n        ^\n'
2023-09-08 22:25:34,493 (71342/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-09-08 22:25:34,493 (71342/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-09-25 10:24:19,376 (51370/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-09-25 10:24:19,376 (51370/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-09-25 10:24:24,056 (51370/MainThread) pgcli.pgexecute ERROR - sql: '\x11\x1bddquit', error: SyntaxError('syntax error at or near "\x11"\nLINE 1: \x11\x1bddquit\n        ^')
2023-09-25 10:24:24,059 (51370/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.5.0_1/libexec/lib/python3.11/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "\x11"\nLINE 1: \x11\x1bddquit\n        ^\n'
2023-09-25 10:24:36,238 (51400/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-09-25 10:24:36,238 (51400/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-06 11:08:10,091 (52184/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-06 11:08:10,091 (52184/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-01-04 11:19:42,119 (4072/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2024-01-04 11:19:42,119 (4072/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
